### ISSUE TITLE
6. lab örneği

### ISSUE THREAD

**Issue by irem6142** [elifbeyzatok00/yazilim-tasarim-desenleri-turkce-kaynak#1]
Elifciğim ,ellerine sağlık çok güzel olmuş da 6. lab/1 örneği neden hepsini bir User classı  içine yazdın ayrı ayrı yazsan daha okunaklı olmaz mıydı? :)

**Comment by elifbeyzatok00** [comment]
> Elifciğim ,ellerine sağlık çok güzel olmuş da 6. lab/1 örneği neden hepsini bir User classı içine yazdın ayrı ayrı yazsan daha okunaklı olmaz mıydı? :)

Güzel bir noktaya değinmişsin. Dediğin gibi ayrı ayrı classlar içinde yazsak daha okunaklı ve kullanışlı olur. Fakat derste verilen task ı en basit şekilde kodlamaya çalıştığımız için hepsini tek class'ta yazıp geçmiştik. Yine de doğru kullanım senin söylediğin gibi olmalı. Uyardığın için teşekkür ederim😊🙏🏽
